CREATE TABLE [dbo].[INVOICE_ITEM]
(
    [InvItemID] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [InvoiceID] INT NOT NULL, 
    [ServiceID] INT NOT NULL, 
    [StartOperationID] INT NOT NULL, 
    [StopOperationID] INT NOT NULL, 
    [StartDate] DATETIMEOFFSET NOT NULL,
    [EndDate] DATETIMEOFFSET NOT NULL,
    [StartMonth] SMALLINT NOT NULL,
    [EndMonth] SMALLINT NOT NULL,
    [StartYear] SMALLINT NOT NULL,
    [EndYear] SMALLINT NOT NULL,
    [Value] DECIMAL(18,4) NOT NULL,
    [Finished] SMALLINT NULL,
    CONSTRAINT FK_INVOICE_ITEM_INVOICE FOREIGN KEY (InvoiceID) REFERENCES [dbo].[INVOICE](InvoiceID),
    CONSTRAINT FK_INVOICE_ITEM_OPERATION_START FOREIGN KEY (StartOperationID) REFERENCES [dbo].[OPERATION](OperationID),
    CONSTRAINT FK_INVOICE_ITEM_OPERATION_STOP FOREIGN KEY (StopOperationID) REFERENCES [dbo].[OPERATION](OperationID)
);
GO

CREATE NONCLUSTERED INDEX [IX_INVOICE_ITEM_InvoiceID] ON [dbo].[INVOICE_ITEM] ([InvoiceID]);
GO
CREATE NONCLUSTERED INDEX [IX_INVOICE_ITEM_StartMonth] ON [dbo].[INVOICE_ITEM] ([StartMonth]);
GO
CREATE NONCLUSTERED INDEX [IX_INVOICE_ITEM_EndMonth] ON [dbo].[INVOICE_ITEM] ([EndMonth]);
GO
CREATE NONCLUSTERED INDEX [IX_INVOICE_ITEM_StartYear] ON [dbo].[INVOICE_ITEM] ([StartYear]);
GO
CREATE NONCLUSTERED INDEX [IX_INVOICE_ITEM_EndYear] ON [dbo].[INVOICE_ITEM] ([EndYear]);
GO
