CREATE TABLE [dbo].[OPERATION]
(
    [OperationID] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [ServiceID] INT NOT NULL, 
    [CustomerID] INT NOT NULL, 
    [Quantity] DECIMAL(18, 4) NOT NULL, 
    [PricePerDay] DECIMAL(18, 4) NULL, 
    [Date] DATETIMEOFFSET NOT NULL, 
    [Month] SMALLINT NOT NULL, 
    [Year] SMALLINT NOT NULL, 
    [Type] SMALLINT NOT NULL
);
GO

CREATE NONCLUSTERED INDEX [IX_OPERATION_ServiceID] ON [dbo].[OPERATION] ([ServiceID]);
GO
CREATE NONCLUSTERED INDEX [IX_OPERATION_CustomerID] ON [dbo].[OPERATION] ([CustomerID]);
GO
CREATE NONCLUSTERED INDEX [IX_OPERATION_Month] ON [dbo].[OPERATION] ([Month]);
GO
CREATE NONCLUSTERED INDEX [IX_OPERATION_Year] ON [dbo].[OPERATION] ([Year]);
GO
CREATE NONCLUSTERED INDEX [IX_OPERATION_Type] ON [dbo].[OPERATION] ([Type]);
GO
